# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .RunTests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

  testUI:
    needs: build
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - run: dotnet build
    - name: Ensure browsers are installed
      run: pwsh /home/runner/work/OrangeHRMDariaEremina/OrangeHRMDariaEremina/OrangeHRMDariaEremina/bin/Debug/net7.0/playwright.ps1 install --with-deps
    - name: Run UI tests
      run:  dotnet test --filter OrangeHRMDariaEremina.Tests.UITest
  
  testAPI:
    needs: testUI
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - run: dotnet build
    - name: Ensure browsers are installed
      run: pwsh /home/runner/work/OrangeHRMDariaEremina/OrangeHRMDariaEremina/OrangeHRMDariaEremina/bin/Debug/net7.0/playwright.ps1 install --with-deps
    - name: Run API tests
      run:  dotnet test --filter OrangeHRMDariaEremina.Tests.APITest
  report:
    needs: testAPI
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
      - name: Publish Allure report
        uses: marketplacesolutions/allure-report-action@v1.0.1
        with:
          allure_results: /home/runner/work/OrangeHRMDariaEremina/OrangeHRMDariaEremina/OrangeHRMDariaEremina/bin/Debug/net7.0/allure-results
          gh_pages_branch: gh-pages
          report_folder: allure-report
  
